name: GPG Signing Workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install GPG
        run: |
          sudo apt-get update
          sudo apt-get install -y gnupg
 
      - sname: List GPG keys
        run: |
          gpg --list-secret-keys --keyid-format LONG
        shell: /bin/bash

      - name: Configure Git to sign commits
        run: |
          git config --global user.signingkey <KEY_ID>
          git config --global commit.gpgSign true
        shell: /bin/bash

      - name: Sign a commit
        run: |
          git commit -S -m "Signing a commit"
        shell: /bin/bash