name: Release new version to Maven Central
on:
  pull_request:
    branches: [ master ]
  push:
    branches: [master]
jobs:
  release-maven-central:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Import GPG signing key 2
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.MAVEN_SIGNING_KEY }}
          passphrase: ${{ secrets.MAVEN_SIGNING_KEY_PASSPHRASE }}
      - name: Set up Maven settings
        run: |
          mkdir -p ~/.m2
          echo "<settings>
            <servers>
              <server>
                <id>ossrh</id>
                <username>${{ vars.MVN_CENTRAL_USERNAME }}</username>
                <password>${{ secrets.MVN_CENTRAL_PASSWORD }}</password>
              </server>
            </servers>
          </settings>" > ~/.m2/settings.xml
      - name: Install JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
          server-id: maven-central-release
          server-username: MVN_CENTRAL_USERNAME
          server-password: MVN_CENTRAL_PASSWORD
      - name: Calculate version
        id: calculate-version
        uses: bitshifted/git-auto-semver@v1
        with:
          create_tag: true
      - name: Release to Maven repo
        run: |
          mvn clean -Dgpg.keyname=${{ secrets.GPG_KEY_NAME }} -Dgpg.passphrase=${{ secrets.MAVEN_SIGNING_KEY_PASSPHRASE }} \
              -Drevision=1.0.24 deploy
        env:
          MVN_CENTRAL_USERNAME: ${{ vars.MVN_CENTRAL_USERNAME }}
          MVN_CENTRAL_PASSWORD: ${{ secrets.MVN_CENTRAL_PASSWORD }}