---
name: CI/CD Workflow
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: "21"
      - name: Add additional Maven server to settings.xml
        run: |
		  echo "${{ vars.SETTINGS_XML }}" > ~/.m2/settings.xml
		
      - name: Display modified settings.xml
        run: cat ~/.m2/settings.xml
      - name: Import GPG Key
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" > private_key.asc
          gpg --batch --import private_key.asc
        shell: bash
      - name: Configure GPG
        run: |
          echo "GPG_TTY=$(tty)" >> $GITHUB_ENV
          echo "use-agent" >> ~/.gnupg/gpg.conf
      - name: Build with Maven
        run: mvn clean deploy -s ~/.m2/settings.xml -Dgpg.passphrase=Escol@1979270881 --batch-mode -X
