---
name: Publish package to the Maven Central Repository
on:
 push:
   branches:
     - master
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Maven Central Repository
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: temurin
          server-id: ossrh
          server-username: ${{ vars.MVN_CENTRAL_USERNAME }}
          server-password: ${{ secrets.MVN_CENTRAL_PASSWORD }}
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}  # Use segredo para passphrase

      # Adicionando um passo de debug para verificar a chave GPG
      #- name: Debug GPG Key
      #  run: |
      #    echo "${{ secrets.GPG_PRIVATE_KEY }}" | base64 --decode > private_key.asc
      #    gpg --batch --import private_key.asc || (echo "Failed to import GPG key" && exit 1)
      #  env:
      #    GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Display modified settings.xml
        run: cat ~/.m2/settings.xml

      - name: Set version
        run: mvn versions:set -DnewVersion=${{ github.event.release.tag_name }}

      - name: Publish package
        run: mvn deploy -P release -s /home/runner/.m2/settings.xml
        env:
          MAVEN_USERNAME: ${{ vars.MVN_CENTRAL_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MVN_CENTRAL_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}  # Use segredo para passphrase