---
name: CI/CD Workflow
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: "17"
      - name: Add additional Maven server to settings.xml
        run: |
          echo "Adding additional Maven server to settings.xml"
          sed -i '/<\/servers>/i\
              <server>\
                <id>ossrh</id>\
                <username>'"${{ vars.MVN_CENTRAL_USERNAME }}"'</username>\
                <password>'"${{ secrets.MVN_CENTRAL_PASSWORD }}"'</password>\
              </server>' ~/.m2/settings.xml
      - name: Display modified settings.xml
        run: cat ~/.m2/settings.xml
        env:
          OSSRH_USERNAME: ${{ vars.MVN_CENTRAL_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.MVN_CENTRAL_PASSWORD }}
      - name: Build with Maven
        run: ls
      - name: Ready .settings.xml
        run: cat ~/.m2/settings.xml
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: "17"
      - name: Import GPG Key
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | base64 --decode > private_key.asc
          gpg --batch --import private_key.asc
        shell: bash
      - name: Configure GPG
        run: |
          echo "GPG_TTY=$(tty)" >> $GITHUB_ENV
          echo "default-key Escol@1979270881" >> ~/.gnupg/gpg.conf
          echo "use-agent" >> ~/.gnupg/gpg.conf
      - name: Deploy to Maven Central
        run: mvn -X deploy
        env:
          OSSRH_USERNAME: ${{ vars.MVN_CENTRAL_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.MVN_CENTRAL_PASSWORD }}
