name: CI/CD Workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Add additional Maven server to settings.xml v1
	    run: |
		  echo "Adding additional Maven server to settings.xml"
		  xmlstarlet ed -L -s "/settings/servers" -t elem -n "server" \
		    -s "/settings/servers/server[last()]" -t elem -n "id" -v "ossrh" \
			-s "/settings/servers/server[last()]" -t elem -n "username" -v "${{ vars.OSSRH_USERNAME }}" \
			-s "/settings/servers/server[last()]" -t elem -n "password" -v "${{ secrets.OSSRH_PASSWORD }}" \
			~/.m2/settings.xml
        env:
          OSSRH_USERNAME: ${{ vars.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}

      - name: Build with Maven
        run: mvn clean

      - name: Ready .settings.xml
        run: cat ~/.m2/settings.xml

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Import GPG Key
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | base64 --decode > private_key.asc
          gpg --batch --import private_key.asc
        shell: bash

      - name: Deploy to Maven Central
        run: mvn clean
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}