name: GPG Signing Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install GPG
        run: |
          sudo apt-get update
          sudo apt-get install -y gnupg
      
      - name: Import GPG key
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | base64 --decode > private_key.asc
          gpg --batch --import private_key.asc
        shell: /bin/bash

      - name: Configure Git to sign commits
        run: |
          git config --global user.signingkey marcelo.utfpr@me.com
          git config --global commit.gpgSign true
        shell: /bin/bash

      - name: Sign a commit
        run: |
          git commit -S -m "Signing a commit"
        shell: /bin/bash