---
name: Publish package to the Maven Central Repository
on:
  push:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: temurin
          server-id: ossrh
          server-username: m4rc310 #${{ vars.MVN_CENTRAL_USERNAME }}
          server-password: Escol@1979270881 #${{ secrets.MVN_CENTRAL_PASSWORD }}
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
      - name: Create settings-security.xml <~ OK
        run: echo "${{ vars.SETTINGS_SECURITY_XML }}" > ~/.m2/settings-security.xml
        env:
          SETTINGS_SECURITY_XML: ${{ vars.SETTINGS_SECURITY_XML }}
      - name: Display modified settings.xml
        run: |
          cat ~/.m2/settings.xml
          cat ~/.m2/settings-security.xml
      - name: Set version
        run: mvn versions:set -DnewVersion=1.0.25
      - name: Publish package
        run: mvn clean deploy -Dgpg.passphrase=Escol@1979270881 --batch-mode -X -s ~/.m2/settings-security.xml
        env:
          MAVEN_USERNAME: ${{ vars.MVN_CENTRAL_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MVN_CENTRAL_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
