---
name: Publish package to the Maven Central Repository
on:
  push:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: temurin
      - name: Add additional Maven server to settings.xml
        run: >
          echo "Adding additional Maven server to settings.xml"
          sed -i '/<\/servers>/i\
                <server>\
                  <id>ossrh</id>\
                  <username>'"${{ vars.MVN_CENTRAL_USERNAME }}"'</username>\
                  <password>'"${{ secrets.MVN_CENTRAL_PASSWORD }}"'</password>\
                </server>' ~/.m2/settings.xml
      - name: Display modified settings.xml
        run: cat ~/.m2/settings.xml
      - name: Set version
        run: |
          echo ${{ vars.MVN_CENTRAL_USERNAME }}
          echo ${{ secrets.MVN_CENTRAL_PASSWORD }}
      - name: Publish package
        run: ls
        env:
          MAVEN_USERNAME: ${{ vars.MVN_CENTRAL_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MVN_CENTRAL_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: Escol@1979270881
