---
name: Test 
on:
  push:
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: "21"
      - name: Add additional Maven server to settings.xml
        run: |
          echo "Adding additional Maven server to settings.xml"
          sed -i '/<\/servers>/i\
              <server>\
                <id>ossrh</id>\
                <username>'"${{ vars.MVN_CENTRAL_USERNAME }}"'</username>\
                <password>'"${{ secrets.MVN_CENTRAL_PASSWORD }}"'</password>\
              </server>' ~/.m2/settings.xml
      - name: Ready .settings.xml
        run: cat ~/.m2/settings.xml
      - name: Import GPG Key
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" > private_key.asc
          gpg --batch --import private_key.asc
        shell: bash
      - name: Get TAG
        id: get_tag
        run: echo "TAG=$(git describe --tags --exact-match)" 	
      - name: Set Maven Version
        id: set_version
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo ${GITHUB_REF_NAME#v}
          echo "mvn versions:set -DnewVersion=${{ env.VERSION }}"
 #     - name: Set Maven Version
 #       run: mvn versions:set -DnewVersion=${{ github.ref_name }}
      - name: Configure GPG
        run: |
          echo "GPG_TTY=$(tty)" >> $GITHUB_ENV
          echo "use-agent" >> ~/.gnupg/gpg.conf
#      - name: Build with Maven
#        run: mvn clean deploy -s ~/.m2/settings.xml -Dgpg.passphrase=${{
#          secrets.GPG_PASSPHRASE }} --batch-mode
